import {useMemo,useState} from "react";
import type {Candidate,Category,ScanReport} from "../types";
import {zh} from "../i18n";
import {size} from "../format";

const categories:Category[]=["application-caches","developer-caches","project-dependencies","logs","crash-reports","download-leftovers","other"];
interface Props{report:ScanReport;selected:Set<string>;onSelected:(value:Set<string>)=>void;onBack:()=>void;onClean:()=>void;cleaning:boolean}
export function ResultsStep({report,selected,onSelected,onBack,onClean,cleaning}:Props){
 const [query,setQuery]=useState(""),[riskFilter,setRiskFilter]=useState<"all"|"low"|"review">("all"),[categoryFilter,setCategoryFilter]=useState<Category|null>(null);
 const visible=useMemo(()=>report.candidates.filter(candidate=>(riskFilter==="all"||candidate.risk===riskFilter)&&(!categoryFilter||candidate.category===categoryFilter)&&(!query||`${candidate.path} ${candidate.reason}`.toLowerCase().includes(query.toLowerCase()))),[report,riskFilter,categoryFilter,query]);
 const sequence=useMemo(()=>new Map(visible.map((candidate,index)=>[candidate.id,index+1])),[visible]);
 const picked=report.candidates.filter(candidate=>selected.has(candidate.id));
 const toggle=(id:string)=>{const next=new Set(selected);next.has(id)?next.delete(id):next.add(id);onSelected(next)};
 const toggleGroup=(items:Candidate[])=>{const next=new Set(selected),all=items.every(item=>next.has(item.id));items.forEach(item=>all?next.delete(item.id):next.add(item.id));onSelected(next)};
 return <div className="results-layout"><aside className="filters"><button className={riskFilter==="all"&&!categoryFilter?"active":""} onClick={()=>{setRiskFilter("all");setCategoryFilter(null)}}>{zh.all}<span>{report.candidates.length}</span></button><button className={riskFilter==="low"&&!categoryFilter?"active":""} onClick={()=>{setRiskFilter("low");setCategoryFilter(null)}}>{zh.low}<span>{report.candidates.filter(item=>item.risk==="low").length}</span></button><button className={riskFilter==="review"&&!categoryFilter?"active":""} onClick={()=>{setRiskFilter("review");setCategoryFilter(null)}}>{zh.review}<span>{report.candidates.filter(item=>item.risk==="review").length}</span></button>{categories.map(category=><button className={categoryFilter===category?"active":""} key={category} onClick={()=>{setRiskFilter("all");setCategoryFilter(category)}}>{zh.category[category]}<span>{report.candidates.filter(item=>item.category===category).length}</span></button>)}</aside><section className="results-screen"><div className="screen-heading"><div><h2>{zh.resultsTitle}</h2><p>{zh.resultsHint}</p></div><button className="ghost" disabled={cleaning} onClick={onBack}>{zh.chooseAgain}</button></div>{report.warnings.map(warning=><div className="warning-bar" key={warning}>{zh.scanWarning}{warning}</div>)}<input className="search" placeholder={zh.search} value={query} onChange={event=>setQuery(event.target.value)}/><div className="candidate-list">{(["low","review"] as const).map(risk=>categories.map(category=>{const items=visible.filter(item=>item.risk===risk&&item.category===category).sort((a,b)=>b.sizeBytes-a.sizeBytes);if(!items.length)return null;return <section key={`${risk}-${category}`}><div className="group"><div><span className={`risk ${risk}`}>{risk==="low"?zh.low:zh.review}</span><h3>{zh.category[category]}</h3><small>{items.length} {zh.itemUnit} · {size(items.reduce((sum,item)=>sum+item.sizeBytes,0))}</small></div><button onClick={()=>toggleGroup(items)}>{items.every(item=>selected.has(item.id))?zh.unselectGroup:zh.selectGroup}</button></div>{items.map(item=><label className="candidate" key={item.id}><input aria-label={`${zh.select} ${item.path}`} type="checkbox" checked={selected.has(item.id)} onChange={()=>toggle(item.id)}/><span className="index">{String(sequence.get(item.id)??0).padStart(2,"0")}</span><div className="candidate-copy"><strong>{item.path.split("/").pop()}</strong><code>{item.path}</code><p>{item.reason}</p></div><div className="meta"><b>{size(item.sizeBytes)}</b><span>{new Date(item.modifiedAt*1000).toLocaleDateString(zh.locale)}</span></div></label>)}</section>}) )}</div><footer className="selection-footer"><div><b>{zh.selected} {picked.length} {zh.itemUnit}</b><span>{size(picked.reduce((sum,item)=>sum+item.sizeBytes,0))}</span></div><button className="primary" disabled={!picked.length||cleaning} onClick={onClean}>{zh.move}</button></footer></section></div>;
}
